### ISSUE TITLE
Support mentions

### ISSUE THREAD

**Issue by donaghhorgan** [filipre/signalbot#13]
It would be nice if the `Message` class had a `mentions` method that you could use to check whether a given message mentioned a given user, e.g. something along the lines of this:

```python
message = Message.parse(...)
if message.mentions("+1234567890"):
    do_something()
```

I'd be happy to contribute a PR if you're open to it?

**Comment by tzabian** [comment]
@filipre the above PR adds `mentions` to the Message container. Also added `raw_message` which currently always returns `None`

**Comment by filipre** [comment]
Thank you again @tzabian . `mentions` will be available in the next release. 

Right now, `mentions` contains a list of dict looking like this
```
{'name': '+49123456789', 'number': '+49123456789', 'uuid': 'asdfasdfasdf-asdfasdfasdf-asdf-asdfasd', 'start': 9, 'length': 1}
```
I may add the check from OP at some point later

**Comment by Era-Dorta** [comment]
Mentions are already supported, closing.
