### ISSUE TITLE
[Feature Request] Support reply by bot

### ISSUE THREAD

**Issue by Kariton** [filipre/signalbot#17]
As far as I understand there is no way to reply to a message.

It would be nice if the bot could reply to the `command` itself, or other messages.

EDIT: you actually can read reply's. And this solves a big portion of my initial description.

**Comment by Kariton** [comment]
Reply's can indeed be read as such:

``ctx.message.raw_message.envelope.dataMessage.quote```
```json
{
    "id": 1234567890,
    "author": "REDACTED",
    "authorNumber": "REDACTED",
    "authorUuid": "REDACTED",
    "text": "message that I replied to",
    "attachments": []
}
```

**Comment by Kariton** [comment]
well: https://github.com/bbernhard/signal-cli-rest-api/issues/261

**Comment by Kariton** [comment]
After looking into it a bit more i found this:
https://github.com/bbernhard/signal-cli-rest-api/pull/208

> Added support for missing send arguments:
> 
> Mentions
> Quote timestamp
> Quote author
> Quote message
> Quote mentions

but i don't think this is currently supported here.

**Comment by filipre** [comment]
I just implemented it. Can you take a look [here](https://github.com/filipre/signalbot/issues/30#issuecomment-1676319406)?

**Comment by Kariton** [comment]
That does work.
Thank you very much!

I would like to keep it open until the 0.8.0 is released. :)

**Comment by filipre** [comment]
Released
