### ISSUE TITLE
support `c.reply(...)`

### ISSUE THREAD

**Issue by richtier** [filipre/signalbot#30]
Would be great to be able to reply to a message (similar to reacting), but text instead of emoji

I'm happy to contribute this feature, if I'm given some clues as to how it could be done

**Comment by filipre** [comment]
Hi! I just implemented it. I assume you were referring to quote replies, right?

Can you try out this test package and let me know if it works?
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple signalbot==0.8.0a1691923863
```
I also changed the bot API a bit. `.listen` is not necessary anymore and you can also run commands in private chats. [Here](https://github.com/filipre/signalbot/tree/private-chats/example) is an examle. It also contains an example how to use `c.reply` but it has the same signature as `c.send`. If it works for you, I'd release it very soon

**Comment by richtier** [comment]
fantastic thanks I'll give it a go and report back

**Comment by richtier** [comment]
works great thanks so much :)
