### ISSUE TITLE
How to download images attached to a message?

### ISSUE THREAD

**Issue by qwertyexp** [filipre/signalbot#31]
I tried reading Context.message.base64_attachments, but it only contains metadata, not the image itself.

`{'envelope': {'source': '+xxxxx', 'sourceNumber': '+xxxx', 'sourceUuid': '245c2a4e-706c-4ed0-b5db-a4212adf02b0', 'sourceName': 'tommaso', 'sourceDevice': 3, 'timestamp': 1691597569365, 'syncMessage': {'sentMessage': {'destination': None, 'destinationNumber': None, 'destinationUuid': None, 'timestamp': 1691597569365, 'message': 'stampa giovanni-ciao', 'expiresInSeconds': 0, 'viewOnce': False, 'attachments': [{'contentType': 'image/png', 'filename': 'Schermata da 2023-07-27 15-21-23.png', 'id': 'xxxx', 'size': 67513}], 'groupInfo': {'groupId': xxxx', 'type': 'DELIVER'}}}}, 'account': '+xxxx', 'subscription': 0}`

**Comment by jbaiter** [comment]
Has this been implemented? I still see a TODO in the source code for the base64_attachments field on the message type, and it doesn't seem to be set from anywhere.

**Comment by Era-Dorta** [comment]
Hi, I've implemented this in this PR https://github.com/filipre/signalbot/pull/70 You can do `ctx.message.attachments_filenames` to get the file names.

**Comment by Era-Dorta** [comment]
The PR has been merged, the naming changed a bit, it is now `ctx.message.attachments_local_filenames`
