### ISSUE TITLE
Support private chats

### ISSUE THREAD

**Issue by filipre** [filipre/signalbot#5]
Currently, signalbot only supports groups by using `listen(group_id, group_secret)` but we should support individual chats as well. Some rough ideas:
- ~~`listen(group_id, group_secret)` and `listenGroup(group_id, group_secret)`: listen for given group~~
- ~~`listenUser(phone_number)`: listen for given user~~
- ~~`listen(id: str, internal_id: Optional[str] = None)` where `id` and `internal_id` identifies the chat type. If `id` does not start with a `+`, then `internal_id` must be provided~~

To clarify: Can we listen for all users and all groups, without implementing a refresh logic or similar? 
~~- `listenAllUsers()`: Handle all incoming user chats~~
~~- `listenAllGroups()`: Handle all incoming groups by maintaining a dict which keeps track of the mapping between `id` and `internal_id`~~
~~- `listenAll()`: calls `listenAllUsers()` and `listenAllGroups()`~~

~~If we implement `listenAll*()`, we should also have decorators for commands that only apply for specific groups, e.g.~~

```python

from signalbot import Command, triggered, listen

class PasswordCommand(Command):
    def describe(self) -> str:
        return "🔐 Lists all Passwords"

    @triggered("password")
    @listen("group_1=", "group_2=", "+phone_number")
    async def handle(self, c: Context):
        await c.send("password123")
```

## Todos

- [x] Add `listenUser(phone_number)` to support user chats
- ~~[x] Implement `@listen`~~
- [x] Implement `listenGroup()`. Refactor `listen(...)` to make it work with groups and user chats
- ~~[x] Implement `listenAllUsers()`, easy~~
- ~~[x] Implement `listenAllGroups()`, more difficult because of the group API call / cache~~
- ~~[x] Implement `listenAll()`~~

**Comment by filipre** [comment]
Don't have a decorator. Commands should be independent to bot implementation/config. When the bot starts, it should check all groups and keeps a mapping between group's `internal_id` and `id`. Then, we can deprecate the second argument from `bot.listen` and only accept phone numbers or group ids.


Instead of decorator, we should have something like this:
```python
bot.register(command)
bot.register(secret_command, ["+49123456789", "group.asdfasdfadsfasdfasdfasdf"])
```

When `listenAllGroups()` or `listenAll()` is activated, if an `internal_id` is not being found in the group mapping, we need to refresh the groups (and throw an error if something is odd)

**Comment by filipre** [comment]
something like

```python
def register(cmd: Command, users="all", groups="all"):
    pass

# ...

# define who should listen to begin with
bot.listenAllUsers()
bot.listen(group_id, internal_id)

# filter for certain commands
bot.register(cmd)
bot.register(private_cmd, users="all", groups=[])
bot.register(private_cmd, users="all") # alternative
bot.register(group1_cmd, users=[], groups=["group1"])
bot.register(group1_cmd, groups=["group1"]) # alternative
```

for groups, if encounter unknown group id/internal ID, do request to query and update groups

**Comment by Kariton** [comment]
Hey @filipre,

im not totally sure if i understand the upcomming handling (v.0.8.0) correctly.

in the provided examples you define:
- only for groups
- for one specific group by name
- for all groups and one specific contact

the last one is the case im not sure about.
does that mean theat "one specific contact in all groups" - eg. not in private chats - no other member, is able to utilise the command?
or all groups **AND** the unser in private chats?

it would be useful for me if "only user of group - in group" is able to use a command. i have "group moderators" in mind but they might not be a "signal group admin" and are not permitted in other groups.

**Comment by filipre** [comment]
Hi @Kariton,

thanks for your comment. This issue here was really just some scrap paper for me. I settled with the following solution:
- deprecate any `.listen*()` function
- extend `.register` to include phone numbers and group names

For example, the new API for `.register` will look like this:
```python
# enable a chat command for all contacts and all groups
bot.register(PingCommand())

# enable a chat command only for groups
bot.register(FridayCommand(), contacts=False, groups=True)

# enable a chat command for one specific group with the name "My Group"
bot.register(TypingCommand(), groups=["My Group"])

# chat command is enabled for all groups and one specific contact
bot.register(TriggeredCommand(), contacts=["+490123456789"], groups=True)
```

What do you think about this approach? I like that you don't need to figure out the group ID and secret anymore and can use the group name instead.

>or all groups AND the unser in private chats?

I was planning this case. What you could do instead is to check if the `message.source` equals a given number (the group moderator) and only react then, similar to the way we currently handle chat commands. We could also add/modify a decorator similar to the `@triggered` decorator.

**Comment by Kariton** [comment]
hey ho,

i think you slightly misunderstood me,
what i referenced are your examples from the branch  `private-chats` - where you copied the code from. :)
i already use the test release succsessfuly for my little project (still learning A LOT based on your rather simple framework).

regarding your questin, the idea of group names is nice. i like it.
but an ID should still be possible... because _my_ goup members sometimes change the name like their underwear.
eather way, _i_ (currently) dont use the group name.

> What you could do instead is to check if the message.source equals a given number [...] similar to the way we currently handle chat commands.

i would rather perfer a way to do this right within the `.register` instead of the command itself.
this would make it configurable, hardcoding stuff is not that friendly - especially if those commands should get shared.

this way the bot can be "restarted" from an outer function with new settings (currently i just plan to kill it - an implemented save shutdown / restart is out of scope here).

<details>
<summary>open for more context on how i want to use signalbot</summary>

[WIP - does not work ATM]:
```py
def load_config():
#    with open("config.yaml", "r") as config_file:
#        config = yaml.safe_load(config_file)

    config_yaml = """
    custom_commands:
      - name: CustomCommand1
        contacts:
          - +123456789
          - +987654321
        groups: false
      - name: CustomCommand2
        arguments: {
            some_arg_key: arg_value
        }
        contacts:
          - +987654321
        groups: true
    """
    config = yaml.safe_load(config_yaml)

    return config

def main():
    commands = load_config()
    signal_service = os.environ["SIGNAL_SERVICE"]
    phone_number = os.environ["PHONE_NUMBER"]

    config = {
        "signal_service": signal_service,
        "phone_number": phone_number,
        "storage": {
            "redis_host": 'redis',
            "redis_port": 6379
        }
    }
    bot = SignalBot(config)

    for command_config in commands.get("custom_commands", []):
        command_name = command_config["name"]
        command_class = globals().get(command_name)
        if command_class:
            arguments = command_config.get("arguments", {})
            instance = command_class(**arguments)
            bot.register(
                instance,
                contacts=command_config.get("contacts", []),
                groups=command_config.get("groups", False),
            )
    bot.start()
```


</details>

my question was more focused on the "permission" handling.

## it looks like it works like this;
```py
bot.register(CustomCommand(), contacts=['+123456789','+987654321'], groups=True)
```
"the contacts in private chat AND all groups"
the user "+123456789" and "+987654321" can message the bot privately, and everybody in all groups.

```py
bot.register(CustomCommand(), contacts=['+123456789','+987654321'], groups=False)
```
"ONLY contacts in private chat"
this way only the contacts listed are able to interact - privately.

## what i want:
```py
bot.register(CustomCommand(), contacts=['+123456789','+987654321'], groups=True, contacts_exclusive=True)
```
"contacts in private chat AND ONLY those contacts in groups"
this way only the contacts listed are able to interact - privately and within every group.

## another useful thing will be:
```py
bot.register(CustomCommand(), contacts=['+123456789','+987654321'], groups=True, contacts_exclusive=True, group_admins=True)
```
"contacts in private chat AND those contacts in groups AND group admins"
this way only the contacts listed and group admins are able to interact - privately for contacts and within every group.

## to utilise group ids instead of names:
```py
bot.register(CustomCommand(), contacts=['+123456789','+987654321'], groups=False, group_ids=['asdfghjkl', 'lkjhgfdsa'], contacts_exclusive=True, group_admins=True)
```
`groups` and `group_ids` are mutually exclusive and conflict with each other - groups schould be ignored.
like when the params are `groups=False, group_ids=['someid']`

**Comment by filipre** [comment]
>but an ID should still be possible... because my goup members sometimes change the name like their underwear.
eather way, i (currently) dont use the group name.

I see, I'll add `group_ids` I think. It also solves the issue when two groups with the same name exist. 

>it looks like it works like this [...]

Yes, that's what I intended and believe has the greater use case. But I understand your case, too and it makes sense to have it in the command initialization and not in the command definition. I still want to keep the `.register` method very simple though. You could also have a wrapper class, maybe something like this (untested) below. Though I don't like that it is very coupled to the `Command` structure. 

```python
class AdminCheck(Command):
    def __init__(self, cmd: Command, admins: list = None):
        self._cmd = cmd
        self._admins = admins if admins else []

    async def handle(self, c: Context):
        if c.message.source in self._admins:
            return await self._cmd.handle()

    def setup(self):
        self._cmd.setup()

    def describe(self) -> str:
        return self._cmd.describe()

# ...
admins = ["+49123456789"]
bot.register(AdminCheck(CustomCommand(), admins), contacts=True, groups=True)
```

Or, thinking out of the blue, a very general solution would be passing a lambda that performs a check on a message

```python
def is_privileged(msg: Message) -> bool:
    return msg.source == "+49123456789"

bot.register(CustomCommand(), contacts=[], groups=["Hello World"], f=is_privileged) # run only for "+49123456789" in "Hello World"
bot.register(CustomCommand(), f=lambda msg: msg.source == "+4912345678") # run only for "+49123456789" in all groups and the private chat
```

This approach also lets you have a configurable prefix, if you don't want to have this logic in the handle function

```python
def has_prefix(prefix: str):
    return lambda msg: msg.text[0] == prefix

bot.register(PingCommand(), contacts=True, groups=True, f=has_prefix("/"))
```

**Comment by Kariton** [comment]
Hey,

big thanks for your suggestions / snippets!

regarding the admin:
> class AdminCheck(Command):

`/v1/groups/{number}/{groupid}` will return "admins" as a list of member.
```json
{
  "name": "Test",
  "id": "group.XXX=",
  "internal_id": "XXX=",
  "members": [
    "+987654321",
    "+123987456",
    "+789654123",
    "+3214569789"
  ],
  "blocked": false,
  "pending_invites": [],
  "pending_requests": [],
  "invite_link": "",
  "admins": [
    "+123456789"
  ]
}
```
this is what i have had in mind (dunno if this could be fetched every now and then, to be up to date)

> bot.register(CustomCommand(), f=lambda msg: msg.source == "+4912345678")
> bot.register(PingCommand(), contacts=True, groups=True, f=has_prefix("/"))

WOW. THATS impressive. 😮 🤯 

I love the level of detailed support you provide.
thank you relay much.

```py
bot.register(CustomCommand(), f=lambda msg: msg.source != "+4912345678")
```
will be implementet right away because i did not intend to trigger all of my commands myself. (linked device)

**Comment by filipre** [comment]
>I love the level of detailed support you provide.
thank you relay much.

Thank you 😊

>will be implementet right away because i did not intend to trigger all of my commands myself. (linked device)

I implemented the lambda argument `f` yesterday quite quickly, but did not test it yet. Feel free to experiment with this release:
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple signalbot==0.8.0a1693341065
```
Also instead of having a new argument `group_ids`, I decided to allow group ids in the `groups` argument. Group names can't be longer than 32 characters anyway so there won't be any conflicts, too.

Actually, the bot fetches all groups at the beginning once and I plan to fetch them regularly, too, maybe every 10 minutes or so. You can get them using `bot.groups`, its the array returned by `/v1/groups/{number}`. Just keep in mind that `bot.groups` is only populated after you start `bot.start()` so using the lambda `f` argument won't work here. If you really want to have this outside of `Command.handle`, you could fetch the groups yourself using `await bot._signal.get_groups()` with your own event loop or the `bot._event_loop`. As the names suggest, `_event_loop` and `_signal` are rather meant for internal use but I think it could work.

**Comment by Kariton** [comment]
thanks for that implementation.
looks like i can replace my own _filter_ handling. :)

i actually didnt expect you to implement `f` directly into the lib - will definitly check that out!

what i did is this:
```py
class HelpCommand(Command):
    def __init__(self, msg_filter=None, msg_prefix=None, prefix=None):
        self.msg_filter = msg_filter
        self.__prefix = msg_prefix if msg_prefix is not None else prefix

    def prefix(self):
        if self.__prefix is None:
            return self.cmd()
        else:
            return self.__prefix + self.cmd()

    def cmd(self) -> str:
        return "help"

    async def handle(self, c: Context):
        try:
            if self.msg_filter and callable(self.msg_filter):
                if not self.msg_filter(c.message):
                    return

            if c.message.text.lower().startswith(self.prefix()):
                # stuff
            return

        except Exception as e:
            # TODO: logger
            print(f"An error occurred: {e}")
```
this does combine my requirements for an `f"{prefix}{command}"` and "_filter_".


for some reason i did not know about `bot.groups` (did you mean `bot.get_groups()`?
need to check the code for that hint.
and generally refreshed group information is a nice to have. 

but wouldnt this hacky way _be possible_?
this would querry the groups FOR EACH MESSAGE - inefficient; but this might do the trick in lambda.
```py
lambda msg: any(
    msg.group == group.get("id") and msg.source in group.get("admins", [])
    for group in bot.get_groups()
)
```
e.g.:
```py
bot.register(CustomCommand(),
    f=lambda msg: any(
        msg.group == group.get("id") and msg.source in group.get("admins")
        for group in bot.get_groups()
        )
    )
```
anyway, the whole "is admin" is currently only a "_~required~ feature_" for future me.
ATM i need to get my code from an "its for some reason working" to "can be published" without feeling ashamed.

**Comment by Kariton** [comment]
oh and that `group_ids` are acutally part of `groups` is brilliant!

**Comment by filipre** [comment]
>(did you mean `bot.get_groups()`?

So the `get_groups()` method only exist within `bot._signal` and that's my API wrapper to make all HTTP requests to the signal-cli-rest-api service. When you call `bot.start()` the `bot.groups` property becomes populated by that method. Notice that this is new in the `private-chats` / v0.8 branch.

>this would querry the groups FOR EACH MESSAGE - inefficient; but this might do the trick in lambda.

In your code you'd need to call `bot._signal.get_groups()` (not `bot.get_groups()`, that's undefined) in some event loop, since it's an asynchronous function. I don't think you want that. Defining `HelpCommand` is better since you can access `bot.groups` in the `hanlde` method.

**Comment by Kariton** [comment]
> I implemented the lambda argument f yesterday quite quickly, but did not test it yet. Feel free to experiment with this release

looks like it is working! :)
thank you very much!
