### ISSUE TITLE
Sending Mentions

### ISSUE THREAD

**Issue by Jasper-J-R** [filipre/signalbot#76]
I'm having difficulty sending mentions and would appreciate any help you could provide.

The relevant code is below.
`mentions = [{
                "name": "OBFUSCATED_UUID",
                "number": None,
                "uuid": "OBFUSCATED_UUID",
                "start": 1,
                "length": 1
            }]`
`await c.send("TEXT", None, mentions=mentions)`
I would expect this to produce a mention based on the mentions json that I got when I saved the info from a real mention example, but it does not. Instead I get a `[PingCommand] Error:` in the signal-api-logfile.txt and nothing of note in the docker logs for the rest api.

**Comment by Era-Dorta** [comment]
The API for sending and receiving are slightly different. For sending a mention you should do:

```python
 mentions = [{ "author": "OBFUSCATED_UUID", "start": 1, "length": 1 }]
```

You can check the API for it here https://bbernhard.github.io/signal-cli-rest-api/#/Messages/post_v2_send
